version: "3.7"

services:
  postgres:
    image: "postgres:11.0-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  web:
    build: "."
    depends_on:
      - "postgres"
    ports:
      - "4000:4000"
    command: "./run.sh"
    volumes:
      - "web:/app"

volumes:
  web:
  postgres: {}
  static:
    driver_opts:
      device: "tmpfs"
      type: "tmpfs"
